name: Connect to QEMU and build SIF Img

on:
  push:
    branches:
      - main

jobs:
  run_steps:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.QEMU_SSH_PRIVATE_KEY }}

      - name: Get Raspberry Pi IP
        id: get_ip
        run: echo "IP=${{ secrets.QEMU_PI_IP }}"

      - name: Create unique test dir
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              pi@${{ steps.get_ip.outputs.IP }} 'mkdir test_$(date +\%Y\%m\%d\%H\%M\%S) && cd test_$(date +\%Y\%m\%d\%H\%M\%S)'

      - name: Clone new data
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              pi@${{ steps.get_ip.outputs.IP }} 'git clone https://github.com/aouniR/_node_red_container.git'

      - name: Build Apptainer img
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              pi@${{ steps.get_ip.outputs.IP }} 'apptainer build sif/cont-name.sif _node_red_container/arm64/def-name.def'

      - name: Push Apptainer sif img to Git LFS
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              pi@${{ steps.get_ip.outputs.IP }} 'git lfs track sif/cont-name.sif && git add . && git commit -m "Commit message: $(date +\%Y\%m\%d\%H\%M\%S)" && git push origin main'
